name: rss_reader
description: A Flutter RSS reader app

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  webfeed: ^0.7.0
  url_launcher: ^6.1.12
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  intl: ^0.17.0
  cached_network_image: ^3.2.3
  html: ^0.15.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/placeholder.png 